Tp-promocón-peliculas-cravero/Models/Film.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Tp_promocón_peliculas_cravero.Models;

namespace Tp_promoción_peliculas_cravero.Models
{
    public class Film
    {
        public int Id { get; set; }


        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "El campo es requerido")]
        public string Title { get; set; }


        [Display(Name = "Fecha de estreno")]
        [Required(ErrorMessage = "El campo es requerido")]
        public DateTime ReleaseDate { get; set; }


        [Display(Name = "Imagen de portada")]
        public string Photo { get; set; }


        [Display(Name = "Trailer")]
        [Required(ErrorMessage = "El campo es requerido")]
        public string Trailer { get; set; }


        [Display(Name = "Descripción")]
        [Required(ErrorMessage = "El campo es requerido")]
        public string Summary { get; set; }


        [Display(Name = "Genero")]
        [Required(ErrorMessage = "El campo es requerido")]
        public int? GenderId { get; set; }
        public Gender Genders { get; set; }


        [Display(Name = "En cartelera")]
        public bool billboard { get; set; }

        
        public List<MovieActor> MovieActors { get; set; }

    }
}

Tp-promocón-peliculas-cravero/Controllers/FilmsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Tp_promoción_peliculas_cravero.Models;
using Tp_promocón_peliculas_cravero;

namespace Tp_promocón_peliculas_cravero.Controllers
{
    public class FilmsController : Controller
    {
        private readonly DbConection _context;
        private readonly IWebHostEnvironment env;

        public FilmsController(DbConection context, IWebHostEnvironment env)
        {
            _context = context;
            this.env = env;
        }

        // GET: Films
        public async Task<IActionResult> Index()
        {
            var dbConection = _context.Film.Include(f => f.Genders);
            return View(await dbConection.ToListAsync());
        }

        // GET: Films/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .Include(f => f.Genders)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // GET: Films/Create
        public IActionResult Create()
        {
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "Description");
            return View();
        }

        // POST: Films/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ReleaseDate,Photo,Trailer,Summary,GenderId,billboard")] Film film)
        {
            if (ModelState.IsValid)
            {
                var file = HttpContext.Request.Form.Files;
                if(file != null && file.Count > 0)
                {
                    var filePhoto = file[0];
                    var pathDestine = Path.Combine(env.WebRootPath, "Image\\Movies");

                    if(filePhoto.Length > 0)
                    {
                        var fileDestine = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(filePhoto.FileName);

                        using (var filestrem = new FileStream(Path.Combine(pathDestine, fileDestine), FileMode.Create))
                        {
                            filePhoto.CopyTo(filestrem);
                            film.Photo = fileDestine;
                        };
                    }
                }

                _context.Add(film);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "Description", film.GenderId);
            return View(film);
        }

        // GET: Films/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film.FindAsync(id);
            if (film == null)
            {
                return NotFound();
            }
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "Description", film.GenderId);
            return View(film);
        }

        // POST: Films/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ReleaseDate,Photo,Trailer,Summary,GenderId,billboard,Photo")] Film film)
        {
            if (id != film.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //Para que guarde la foto al editar
                var file = HttpContext.Request.Form.Files;
                if (file != null && file.Count > 0)
                {
                    var filePhoto = file[0];
                    var pathDestine = Path.Combine(env.WebRootPath, "Image\\Movies");

                    if (filePhoto.Length > 0)
                    {
                        var fileDestine = Guid.NewGuid().ToString().Replace("-", "") + Path.GetExtension(filePhoto.FileName);

                        using (var filestrem = new FileStream(Path.Combine(pathDestine, fileDestine), FileMode.Create))
                        {
                            filePhoto.CopyTo(filestrem);

                            //Para eliminar la foto anterior por la nueva
                            string oldFile = Path.Combine(pathDestine, film.Photo ?? null);
                            if (System.IO.File.Exists(oldFile))
                                System.IO.File.Delete(oldFile);
                            film.Photo = fileDestine;
                            
                        };
                    }
                }

                try
                {
                    _context.Update(film);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmExists(film.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GenderId"] = new SelectList(_context.Gender, "Id", "Description", film.GenderId);
            return View(film);
        }

        // GET: Films/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var film = await _context.Film
                .Include(f => f.Genders)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (film == null)
            {
                return NotFound();
            }

            return View(film);
        }

        // POST: Films/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var film = await _context.Film.FindAsync(id);
            _context.Film.Remove(film);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmExists(int id)
        {
            return _context.Film.Any(e => e.Id == id);
        }
    }
}

Tp-promocón-peliculas-cravero/Views/Films/Create.cshtml
@model Tp_promoción_peliculas_cravero.Models.Film

@{
    ViewData["Title"] = "Crear - pelicula";
}

<h1>Crear pelicula</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" asp-controller="Films" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="Photo" class="control-label"></label>
                    <input asp-for="Photo" class="form-control" />
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>*@
            <label>Seleccionar portada:</label>
            <div class="form-group">
                <input asp-for="Photo" type="file" id="selectionImg" class="form-control" />
                <img id="image" src="" alt="Imagen seleccionada" height="80" width="80" />
            </div>
            <div class="form-group">
                <label asp-for="Trailer" class="control-label"></label>
                <input asp-for="Trailer" class="form-control" />
                <span asp-validation-for="Trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderId" class="control-label"></label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="billboard" /> @Html.DisplayNameFor(model => model.billboard)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Crear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al listado</a>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="~/js//images.js"></script>

Tp-promocón-peliculas-cravero/Views/Films/Delete.cshtml
@model Tp_promoción_peliculas_cravero.Models.Film

@{
    ViewData["Title"] = "Borrar - pelicula";
}

<h1>Borrar pelicula</h1>

<h3>¿Estás segura de que quieres borrar esto?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            <img src="~/Image/Movies/@Model.Photo" alt="Imagen de pelicula" height="80" width="80" asp-append-version="true" />
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genders.Description)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.billboard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.billboard)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Regresar al listado</a>
    </form>
</div>

Tp-promocón-peliculas-cravero/Views/Films/Details.cshtml
@model Tp_promoción_peliculas_cravero.Models.Film

@{
    ViewData["Title"] = "Detalles - pelicula";
}

<h1>Detalles pelicula</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            <img src="~/Image/Movies/@Model.Photo" alt="Imagen de pelicula" height="80" width="80" asp-append-version="true" />
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Photo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Trailer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Trailer)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Summary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Summary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genders)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genders.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.billboard)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.billboard)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">Regresar al listado</a>
</div>

Tp-promocón-peliculas-cravero/Views/Films/Edit.cshtml
@model Tp_promoción_peliculas_cravero.Models.Film

@{
    ViewData["Title"] = "Editar - pelicula";
}

<h1>Editar pelicula</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseDate" class="control-label"></label>
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
            @*Foto*@
            @*<div class="form-group">
                <label asp-for="Photo" class="control-label"></label>
                <input asp-for="Photo" class="form-control" />
                <span asp-validation-for="Photo" class="text-danger"></span>
            </div>*@
            <input type="hidden" asp-for="Photo" />
            <div>
                <img src="~/Image/Movies/@Model.Photo" id="image" alt="Imagen de pelicula" height="80" width="80" asp-append-version="true" />
                <input asp-for="Photo" type="file" id="selectionImg" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Trailer" class="control-label"></label>
                <input asp-for="Trailer" class="form-control" />
                <span asp-validation-for="Trailer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Summary" class="control-label"></label>
                <input asp-for="Summary" class="form-control" />
                <span asp-validation-for="Summary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenderId" class="control-label"></label>
                <select asp-for="GenderId" class="form-control" asp-items="ViewBag.GenderId"></select>
                <span asp-validation-for="GenderId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="billboard" /> @Html.DisplayNameFor(model => model.billboard)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Regresar al listado</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="~/js//images.js"></script>

Tp-promocón-peliculas-cravero/Views/Films/Index.cshtml
@model IEnumerable<Tp_promoción_peliculas_cravero.Models.Film>

@{
    ViewData["Title"] = "Peliculas";
}

<h1>Inicio de peliculas</h1>

<p>
    <a asp-action="Create">Crear nueva pelicula</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Photo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Trailer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Summary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genders)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.billboard)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                <img src="~/Image/Movies/@item.Photo" alt="Imagen de pelicula" height="80" width="80" asp-append-version="true"/>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Trailer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Summary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genders.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.billboard)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalles</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Borrar</a>
            </td>
        </tr>
}
    </tbody>
</table>